# Streamlit Secrets Template
# Copy this to Streamlit Cloud secrets section

# Optional: RapidAPI Key for enhanced station search
# rapidapi_key = "your_rapidapi_key_here"

# Note: Google API key is hardcoded in the app
# For production, consider moving it here for security 