def get_comprehensive_station_lookup():
    """Comprehensive station code to name mapping - Auto-generated"""
    return {
        'AGC': 'AGRA CANTT',
        'AHMEDABAD': 'AHMEDABAD JUNCTION',
        'AII': 'AJMER',
        'AJMER': 'AJMER JUNCTION',
        'ALD': 'ALLAHABAD',
        'ALLAHABAD': 'PRAYAGRAJ JUNCTION',
        'AMBALA': 'AMBALA CANTT',
        'AMD': 'AHMEDABAD',
        'AMI': 'AMRAVATI',
        'AMRAVATI': 'AMRAVATI',
        'AMRITSAR': 'AMRITSAR JUNCTION',
        'ANVT': 'ANAND VIHAR TERMINAL',
        'ASANSOL': 'ASANSOL JUNCTION',
        'ASN': 'ASANSOL',
        'ASR': 'AMRITSAR',
        'AURANGABAD': 'AURANGABAD',
        'AWB': 'AURANGABAD',
        'BAM': 'BERHAMPUR',
        'BBS': 'BHUBANESWAR',
        'BCT': 'MUMBAI CENTRAL',
        'BELGAUM': 'BELAGAVI',
        'BERHAMPUR': 'BERHAMPUR',
        'BGM': 'BELGAUM',
        'BGP': 'BHAGALPUR',
        'BHAGALPUR': 'BHAGALPUR JUNCTION',
        'BHAVNAGAR': 'BHAVNAGAR TERMINUS',
        'BHOPAL': 'BHOPAL JUNCTION',
        'BHUBANESWAR': 'BHUBANESWAR',
        'BIKANER': 'BIKANER JUNCTION',
        'BILASPUR': 'BILASPUR JUNCTION',
        'BKN': 'BIKANER',
        'BLR': 'BANGALORE CITY',
        'BPL': 'BHOPAL',
        'BRC': 'VADODARA',
        'BSB': 'VARANASI',
        'BSP': 'BILASPUR',
        'BVC': 'BHAVNAGAR',
        'BZA': 'VIJAYAWADA',
        'CAN': 'KANNUR',
        'CBE': 'COIMBATORE',
        'CDG': 'CHANDIGARH',
        'CHANDIGARH': 'CHANDIGARH',
        'CHN': 'CHENNAI CENTRAL',
        'CLT': 'KOZHIKODE',
        'CNB': 'KANPUR CENTRAL',
        'COIMBATORE': 'COIMBATORE JUNCTION',
        'CR': 'CENTRAL RAILWAY ZONE',
        'CSMT': 'CHHATRAPATI SHIVAJI MAHARAJ TERMINUS',
        'CTC': 'CUTTACK',
        'CUTTACK': 'CUTTACK',
        'DADAR': 'DADAR',
        'DARBHANGA': 'DARBHANGA JUNCTION',
        'DAVANGERE': 'DAVANGERE',
        'DBG': 'DARBHANGA',
        'DBRG': 'DIBRUGARH',
        'DDN': 'DEHRADUN',
        'DEE': 'DELHI SARAI ROHILLA',
        'DEHRADUN': 'DEHRADUN',
        'DEL': 'NEW DELHI',
        'DGR': 'DURGAPUR',
        'DHANBAD': 'DHANBAD JUNCTION',
        'DHN': 'DHANBAD',
        'DIBRUGARH': 'DIBRUGARH',
        'DLI': 'OLD DELHI',
        'DR': 'DADAR',
        'DURG': 'DURG',
        'DURGAPUR': 'DURGAPUR',
        'DVG': 'DAVANGERE',
        'DWARKA': 'DWARKA',
        'DWK': 'DWARKA',
        'ED': 'ERODE',
        'ER': 'EASTERN RAILWAY ZONE',
        'ERNAKULAM': 'ERNAKULAM JUNCTION',
        'ERODE': 'ERODE JUNCTION',
        'ERS': 'ERNAKULAM',
        'FARIDABAD': 'FARIDABAD',
        'FDB': 'FARIDABAD NTC',
        'GAYA': 'GAYA JUNCTION',
        'GCT': 'GHAZIPUR CITY',
        'GGN': 'GURGAON',
        'GHAZIABAD': 'GHAZIABAD',
        'GHY': 'GUWAHATI',
        'GKP': 'GORAKHPUR',
        'GNT': 'GUNTUR',
        'GOA': 'MADGAON',
        'GORAKHPUR': 'GORAKHPUR JUNCTION',
        'GR': 'GULBARGA',
        'GULBARGA': 'KALABURAGI',
        'GUNTUR': 'GUNTUR JUNCTION',
        'GURGAON': 'GURGAON',
        'GUWAHATI': 'GUWAHATI',
        'GWALIOR': 'GWALIOR JUNCTION',
        'GWL': 'GWALIOR',
        'GZB': 'GHAZIABAD',
        'HARIDWAR': 'HARIDWAR',
        'HOWRAH': 'HOWRAH JUNCTION',
        'HUBLI': 'HUBBALLI JUNCTION',
        'HW': 'HARIDWAR',
        'HWH': 'HOWRAH',
        'HYD': 'SECUNDERABAD',
        'HYDERABAD': 'HYDERABAD DECCAN',
        'INDB': 'INDORE',
        'INDORE': 'INDORE JUNCTION',
        'JABALPUR': 'JABALPUR',
        'JAIPUR': 'JAIPUR JUNCTION',
        'JALANDHAR': 'JALANDHAR CITY',
        'JAM': 'JAMNAGAR',
        'JAMNAGAR': 'JAMNAGAR',
        'JAMSHEDPUR': 'TATANAGAR JUNCTION',
        'JAT': 'JAMMU TAWI',
        'JBP': 'JABALPUR',
        'JODHPUR': 'JODHPUR JUNCTION',
        'JORHAT': 'JORHAT TOWN',
        'JP': 'JAIPUR',
        'JRC': 'JALANDHAR',
        'JTTN': 'JORHAT',
        'JU': 'JODHPUR',
        'KALKA': 'KALKA',
        'KALYAN': 'KALYAN JUNCTION',
        'KANNUR': 'KANNUR',
        'KGP': 'KHARAGPUR',
        'KHARAGPUR': 'KHARAGPUR JUNCTION',
        'KKDE': 'KURUKSHETRA',
        'KLK': 'KALKA',
        'KOCHI': 'ERNAKULAM JUNCTION',
        'KOL': 'HOWRAH',
        'KOLHAPUR': 'KOLHAPUR',
        'KOLKATA': 'HOWRAH JUNCTION',
        'KOP': 'KOLHAPUR',
        'KOTA': 'KOTA JUNCTION',
        'KOTTAYAM': 'KOTTAYAM',
        'KOZHIKODE': 'KOZHIKODE',
        'KTYM': 'KOTTAYAM',
        'KURLA': 'KURLA',
        'KURUKSHETRA': 'KURUKSHETRA JUNCTION',
        'KYN': 'KALYAN JUNCTION',
        'LDH': 'LUDHIANA',
        'LKO': 'LUCKNOW',
        'LNL': 'KURLA',
        'LTT': 'LOKMANYA TILAK TERMINUS',
        'LUCKNOW': 'LUCKNOW',
        'LUDHIANA': 'LUDHIANA JUNCTION',
        'MADGAON': 'MADGAON',
        'MADURAI': 'MADURAI JUNCTION',
        'MAO': 'MADGAON',
        'MAQ': 'MANGALORE CENTRAL',
        'MAS': 'CHENNAI CENTRAL',
        'MATHURA': 'MATHURA JUNCTION',
        'MDU': 'MADURAI',
        'MFP': 'MUZAFFARPUR',
        'MS': 'CHENNAI EGMORE',
        'MTJ': 'MATHURA',
        'MUM': 'MUMBAI CENTRAL',
        'MUZAFFARPUR': 'MUZAFFARPUR JUNCTION',
        'MYS': 'MYSORE',
        'MYSORE': 'MYSURU JUNCTION',
        'NAGPUR': 'NAGPUR',
        'NDLS': 'NEW DELHI',
        'NELLORE': 'NELLORE',
        'NGP': 'NAGPUR',
        'NJP': 'NEW JALPAIGURI',
        'NK': 'NASHIK ROAD',
        'NLR': 'NELLORE',
        'NR': 'NORTHERN RAILWAY ZONE',
        'NTSK': 'TINSUKIA',
        'NW': 'NORTH WESTERN RAILWAY ZONE',
        'NZM': 'HAZRAT NIZAMUDDIN',
        'PALAKKAD': 'PALAKKAD JUNCTION',
        'PANVEL': 'PANVEL',
        'PATNA': 'PATNA JUNCTION',
        'PGT': 'PALAKKAD',
        'PN': 'PUNE',
        'PNBE': 'PATNA',
        'PNVL': 'PANVEL',
        'PUNE': 'PUNE JUNCTION',
        'PURI': 'PURI',
        'R': 'RAIPUR',
        'RAIPUR': 'RAIPUR',
        'RAJAHMUNDRY': 'RAJAHMUNDRY',
        'RAJKOT': 'RAJKOT JUNCTION',
        'RANCHI': 'RANCHI',
        'RATLAM': 'RATLAM JUNCTION',
        'RJT': 'RAJKOT',
        'RJY': 'RAJAHMUNDRY',
        'RNC': 'RANCHI',
        'RTM': 'RATLAM',
        'SA': 'SALEM',
        'SALEM': 'SALEM JUNCTION',
        'SBC': 'BANGALORE CITY',
        'SC': 'SECUNDERABAD',
        'SDAH': 'SEALDAH',
        'SEALDAH': 'SEALDAH',
        'SECUNDERABAD': 'SECUNDERABAD JUNCTION',
        'SGUJ': 'SILIGURI',
        'SILIGURI': 'SILIGURI JUNCTION',
        'SOLAPUR': 'SOLAPUR',
        'SR': 'SOUTHERN RAILWAY ZONE',
        'ST': 'SURAT',
        'SUR': 'SOLAPUR',
        'SURAT': 'SURAT',
        'SW': 'SOUTH WESTERN RAILWAY ZONE',
        'TATA': 'JAMSHEDPUR',
        'TCR': 'THRISSUR',
        'TEN': 'TIRUNELVELI',
        'THANE': 'THANE',
        'THRISSUR': 'THRISSUR',
        'TINSUKIA': 'NEW TINSUKIA JUNCTION',
        'TIRUCHIRAPALLI': 'TIRUCHIRAPPALLI',
        'TIRUNELVELI': 'TIRUNELVELI JUNCTION',
        'TIRUPATI': 'TIRUPATI',
        'TNA': 'THANE',
        'TPJ': 'TIRUCHIRAPALLI',
        'TPTY': 'TIRUPATI',
        'TVC': 'TRIVANDRUM CENTRAL',
        'UBL': 'HUBLI',
        'UDHAMPUR': 'UDHAMPUR',
        'UDZ': 'UDAIPUR CITY',
        'UHP': 'UDHAMPUR',
        'UJJAIN': 'UJJAIN JUNCTION',
        'UJN': 'UJJAIN',
        'UMB': 'AMBALA',
        'VADODARA': 'VADODARA JUNCTION',
        'VARANASI': 'VARANASI JUNCTION',
        'VELLORE': 'VELLORE KATPADI JUNCTION',
        'VIJAYAWADA': 'VIJAYAWADA JUNCTION',
        'VISAKHAPATNAM': 'VISAKHAPATNAM',
        'VLR': 'VELLORE',
        'VSG': 'VASCO DA GAMA',
        'VSKP': 'VISAKHAPATNAM',
        'WARANGAL': 'WARANGAL',
        'WL': 'WARANGAL',
        'WR': 'WESTERN RAILWAY ZONE',
        'YESVANTPUR': 'YESVANTPUR JUNCTION',
        'YPR': 'YESVANTPUR',
    }